### ISSUE TITLE
Update embedded cloth config

### ISSUE THREAD

**Issue by linux-leo** [Franck-Nein/Mojangster#4]
I am creating a modpack and realized that other mods can use embedded libaries, it would be great if mojangster used an up to date cloth config libary for this purpose.

net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Cloth Config v5' (cloth-config2) 5.0.38 with version 6.1.48 or later.
Unmet dependency listing:
	 - Mod 'Inventory Control Tweaks' (inventory_control_tweaks) 1.3.12+MC1.18-1.18.1 requires version 6.1.48 or later of mod 'Cloth Config v5' (cloth-config2), but only the wrong version is present: 5.0.38!
		 - Mod 'Cloth Config v5' (cloth-config2) 5.0.38 is being provided through e.g. C:\Users\Claudia\Downloads\mmc-stable-win32\MultiMC\instances\mecraft 1.18\.minecraft\mods\mojangster-1.17-1.18-4.1.2.jar -> META-INF/jars/cloth-config-fabric-5.0.38.jar
Inactive mods:
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Cloth Config v5' (cloth-config2) 5.0.38 with version 6.1.48 or later.
Unmet dependency listing:
	 - Mod 'Inventory Control Tweaks' (inventory_control_tweaks) 1.3.12+MC1.18-1.18.1 requires version 6.1.48 or later of mod 'Cloth Config v5' (cloth-config2), but only the wrong version is present: 5.0.38!
		 - Mod 'Cloth Config v5' (cloth-config2) 5.0.38 is being provided through e.g. C:\Users\Claudia\Downloads\mmc-stable-win32\MultiMC\instances\mecraft 1.18\.minecraft\mods\mojangster-1.17-1.18-4.1.2.jar -> META-INF/jars/cloth-config-fabric-5.0.38.jar
Inactive mods:
	 - mod 'Cloth Basic Math' (cloth-basic-math) 0.5.1, reason: inactive parent mod (nested jar)
	 - mod 'Cloth Config v5' (cloth-config2) 5.0.38, reason: to replace
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d95c8, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 11 more

**Comment by Franck-Nein** [comment]
@linux-leo Sorry for the late response, GitHub doesn't notify me anything about this repo for some reason.
This works for me in both 1.17.x and 1.18.x:
[mojangster-1.17-1.18-4.1.2a.jar](https://github.com/Franck-Nein/Mojangster/releases/download/1.17%2F1.18-4.1.2a/mojangster-1.17-1.18-4.1.2a.jar)
If it gives any error please post it here.

**Comment by linux-leo** [comment]
Thanks!
